### ISSUE TITLE
Feature Request - Autoban on griefwatch condition.

### ISSUE THREAD

**Issue by Momiro** [NilanthAnimosus/Barotrauma---Nilanths-Edits#6]
It would be nice to have everyone who overloaded the reactor to just get automatically banned....

**Comment by NilanthAnimosus** [comment]
Griefwatcher does not have auto banning of any kind (or even auto kicking) because it is not 100% accurate, and technically it never could be.

Based off that alone I've never implemented any form of auto bans or auto kicks for it, there reason its nature is public is to warn players to help in defending themselves via responding or vote kicking when they are in fact legitimately playing.

It was never intended to replace admins, and although people can make mistakes I'm pretty certain I could never code a perfected method to determine if a player is doing something bad or good with a seemingly griefable action.

Code just can't work out intentions. the human component is kind of something a server needs, making this an option would just mean my code handles most of the bans and hosts would likely prefer using a less than infallable system in place of getting actual admins.

Personally I don't want to see servers relying more on unperfectable code bans than admins.

**Comment by Momiro** [comment]
That makes a lot of sense actually, consider this issue resolved.
