### ISSUE TITLE
BTE support?

### ISSUE THREAD

**Issue by MaddestLad** [NilanthAnimosus/Barotrauma---Nilanths-Edits#8]
I want to be able to host BTE with Nilmod but i cant :(

**Comment by NilanthAnimosus** [comment]
it is BTE supported, just you have to set that up yourself in nilmods configs otherwise it will mostly work (But not griefwatcher/campaign autobuy or other obscure features), but the current version I created of nilmod does not work at all with the current legacy version of barotrauma.

you will want to find my topic on nilmod on the undertowgames forums, then check the last posts for a landongamer's version which is an unofficially updated version that BT Public uses - which players can join in the latest legacy as far as I know.

The only issue with BTE is the different item names and such - so if you want nilmod to support it fully, you really just need to know of the item names and types that exist - perhaps using the finditem command as a client/server using nilmod.

From there, you need to setup the griefwatcher at most for the items, nilmod is an executable modification and BTE is a content package modification, the two are usable at the same time as mine edits the base game code and chiko's edits the content said code loads, which my mod makes no changes to and is even designed to be customizable enough to make it work well with BTE (Which other servers have done fine!).

I don't play BTE or know its items, so I wouldn't have a clue what needs to be looked into, but I talked to some hosts of BTE and made sure to keep it compatible where I could for any kind of server one wanted to host.

Best of luck getting it setup, if unsure - perhaps ask in the BTE or undertow discords server chatter sections for help on this.
